# The URL the site will be built for
base_url = "https://atsuzaki.com"

compile_sass = true
highlight_code = true
build_search_index = true

title = "atsuzaki"
theme = "even"

taxonomies = [
    # You can enable/disable RSS
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

[extra]
author = "Katherine Philip"

even_menu = [
    {url = "$BASE_URL", name = "About"},
]

even_title = "atsuzaki"
