base_url = "https://atsuzaki.com/"

compile_sass = true
highlight_code = true
build_search_index = true

title = "Atsuzaki's site"

taxonomies = [
    # You can enable/disable RSS
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

[extra]
author = "Katherine Philip"

even_menu = [
#    {url = "$BASE_URL", name = "About"},
#    {url = "$BASE_URLblog", name = "Blog"},
    {url = "mailto:kphilip@pdx.edu", name = "kphilip@pdx.edu"},
#    {url = "https://types.pl/@atsuzaki", name = "Mastodon"},
    {url = "https://github.com/atsuzaki/", name = "GitHub"},
]

even_title = "atsuzaki"
