base_url = "https://atsuzaki.com/"

compile_sass = true
highlight_code = true
build_search_index = true

title = "Atsuzaki's site"

taxonomies = [
    # You can enable/disable RSS
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

[extra]
author = "Katherine Philip"

even_menu = [
    {url = "$BASE_URL", name = "About"},
#    {url = "$BASE_URLprojects", name = "Projects"},
#    {url = "$BASE_URLblog", name = "Blog"},
]

even_title = "atsuzaki"
